# Site settings
title: "On Software Engineering <br>and Bible Study"
author: "Zhenqiang Li"
description: "This blogs is about some notes in software developing and bible study."
keywords: "Android, Bible"
biography: "I am a Software Engineer at Google" # TODO: add resume "<a href='/assets/cv.pdf'>Résumé</a>."
colophon: "© 2018 by Zhenqiang Li."

baseurl: ""
url: "http://zhenqiang.li"

twitter_username: 
github_username: ryneli
linkedin_username: 
facebook_username: 
google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
